name: "GW"
description: "GW prototyping"

author: "Sam Leon"

url: "https://github.com/noelmas/GW/"
baseurl: "/GW"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: 
ga_tracking_id: 
