name: "GW"
description: "GW prototyping"

author: "Sam Leon"

url: "http://noelmas.github.io/gw"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: 
ga_tracking_id: 
